# Generated by Django 4.2.1 on 2023-05-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_dob_customers_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
