# Generated by Django 4.2.1 on 2023-05-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='street_number',
            field=models.CharField(blank=True, max_length=76, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='street_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
