# Generated by Django 4.2.1 on 2023-05-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customeraddress_street_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerAddress',
            new_name='CustomerAddres',
        ),
    ]
