# Generated by Django 4.2.1 on 2023-05-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_customeraddress_customeraddres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerAddres',
            new_name='CustomerAddress',
        ),
    ]
